apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-rpc-server
  template:
    metadata:
      labels:
        app: chat-rpc-server
    spec:
      serviceAccountName: openim-service-account
      containers:
        - name: openim-chat-rpc-container
          image: 10.88.88.13:81/app/openim-chat-rpc:v260131154910
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: CHATENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_USERNAME
              value: "root"
            - name: CHATENV_MONGODB_PASSWORD
              value: "root123456"

          volumeMounts:
            - name: openim-chat-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 30300
      volumes:
        - name: openim-chat-config
          configMap:
            name: openim-chat-config
