apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-rpc-server
  template:
    metadata:
      labels:
        app: chat-rpc-server
    spec:
      containers:
        - name: openim-chat-rpc-container
          image: 10.88.88.13:81/app/openim-chat-rpc:v260202071219
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: DEPLOYMENT_TYPE
              value: "kubernetes"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_URI
              value: "mongodb://root:root123456@10.88.88.13:27017/openim_v3?authSource=admin"
            - name: MONGO_URI
              value: "mongodb://root:root123456@10.88.88.13:27017/openim_v3?authSource=admin"
            - name: MONGODB_URI
              value: "mongodb://root:root123456@10.88.88.13:27017/openim_v3?authSource=admin"
          
          volumeMounts:
            - name: openim-chat-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 30300
      volumes:
        - name: openim-chat-config
          configMap:
            name: openim-chat-config
